name: Python

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-20.04']

      fail-fast: true
      max-parallel: 3

    steps:
    - uses: actions/checkout@v2

    - name: Dependencies
      run: sudo apt install
        python3-setuptools
        python3-flask
        python3-sqlalchemy

    - uses: TrueBrain/actions-flake8@master
      with:
        ignore: F,W,C90
        only_warn: 1

    - uses: TrueBrain/actions-flake8@master
      with:
        ignore: E

  deb:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-20.04']

      fail-fast: true
      max-parallel: 3

    steps:
    - uses: actions/checkout@v2

    - name: Dependencies
      run: sudo apt install
        python3-all
        python3-stdeb
        dh-python
        python3-setuptools
        python3-flask
        python3-sqlalchemy

    - name: Build
      run: python3 setup.py --command-packages=stdeb.command bdist_deb

    - name: Os version
      id: os_version
      run: |
        source /etc/os-release
        echo ::set-output name=version::$NAME-$VERSION_ID

    - uses: actions/upload-artifact@v2
      with:
        name: ${{ steps.os_version.outputs.version }}-deb-package
        path: deb_dist/*.deb
